name: Schedule parsing test

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event=${{ github.event_name }}"
          date -u
